# Generated by Django 5.1.5 on 2025-01-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Book',
        ),
    ]
